## Referentinnen und Referenten

**Digital Humanities Bern**  
*Introducing the Lecture Series and the Study Programme* — 14. September, Vortragssprache: Englisch

**JProf. Dr. Andreas Weilinghoff** · Universität Koblenz  
*Using and finetuning Whisper for different languages and varieties* — 21. September, Vortragssprache: Englisch

**Florian Busch** · SNF-Projekt «Texting in Time», Universität Bern  
*Vom Screenrecording zum Keylog* / *From Screen Recording to Keylog: Video-Based Reconstruction of Writing Processes in Mobile Messenger Communication* — 28. September, Vortragssprache: Deutsch

**Annemieke Romein** · University of Twente, Enschede  
*HAICu: Co-Creating Meaningful (X)AI with Cultural Heritage Partners* — 05. Oktober, Vortragssprache: Englisch

**Kathryn Rudy** · University of St Andrews, Scotland  
*Manuscript Studies* — 12. Oktober, Vortragssprache: Englisch

**Prof. Dr. Evelyn Gius** · Technische Universität Darmstadt  
*Messunsicherheit als epistemische Ressource in den Digital Humanities* / *Measurement Uncertainty as an Epistemic Resource in the Digital Humanities* — 02. November, Vortragssprache: Deutsch

**Estelle Guéville** · Yale University, USA  
*Making Women's Manuscript Production Count* — 09. November, Vortragssprache: Englisch

**Timon Boehm** · Universität Stuttgart  
*TOPTEXT. Topologische Textanalyse mittels eingebetteter Flussgraphen* / *TOPTEXT. Topological Text Analysis via Embedded Flow Graphs* — 16. November, Vortragssprache: Deutsch

**William Mattingly** · Yale University, USA  
*Visual Language Models* — 07. Dezember, Vortragssprache: Englisch
